### ISSUE TITLE
Scale layout for smaller screens

### ISSUE THREAD

**Issue by heinburger** [murrayju/durak#1]
make the hands look pretty for smaller resolutions

**Comment by heinburger** [comment]
I see there are only 4 spots/players on the `GameBoard` - @murrayju do you want to limit the player count?

**Comment by heinburger** [comment]
nevermind - the mid one is multiple players

**Comment by murrayju** [comment]
There's a practical limit of 8, you can't deal a full hand to everyone if you have more than that. We've played with 6 a bunch, that seems to work well. So we should make sure that 6 looks good on screen, 8 would be gravy...
