### ISSUE TITLE
Make play field (attack and defence area)

### ISSUE THREAD

**Issue by heinburger** [murrayju/durak#3]
we should use this:
https://github.com/atlassian/react-beautiful-dnd

**Comment by heinburger** [comment]
I've used it in another project and I think it would be great for draggin the cards into the play field

**Comment by murrayju** [comment]
👍 that looks great.

**Comment by murrayju** [comment]
I have part of this done, pushed to master. Reading up on react-beautiful-dnd, it seems that it's only recommended specifically for reorderable lists of things. It seems that [react-dnd](https://react-dnd.github.io) is the recommended library for us. I have this partially wired up, but it doesn't seem to be working for some reason. Feel free to fiddle with this...

**Comment by heinburger** [comment]
ah yeah - I guess there would be more freedom with react-dnd, but it is not as nice. That's fine, but isn't this what we have? List of cards in hand, list of attacks/defences combinations

I don't think react-dnd has good mobile support (we need to use the `react-dnd-touch-backend` to support it), but I didnt look into it too far since it was a bit ago

**Comment by murrayju** [comment]
Closing this since the play field is there... making other tickets for improvements.
